rate: {check_subscribers: 1, publish: 10}
objects:
  [
  0.3, 0.3,0.2, 0.15, 0, 0, # surv
  0.35, 0.2,0.2, 0.0, 0, 0, # backpack
  0.1, 0.3,0.2, 0.0, 0, 0, # helm
  0.1, 0.2,0.2, 0.0, 0, 0, # phone
  0.2, 0.4,0.2, 0.0, 0, 0, # rope
  ]
