# objects:
# - {height: 0.3, width: 0.3} # surv
# - {height: 0.35, width: 0.2} # backpack
# - {height: 0.1, width: 0.3} # helm
# - {height: 0.1, width: 0.2} # phone
# - {height: 0.2, width: 0.2} # rope
rate: {check_subscribers: 1, publish: 10}

object_id: 0
objects:
  [
  0.3, 0.3, # surc
  0.35, 0.2, # backpack
  0.1, 0.3, # helm
  0.1, 0.2, # phone
  0.2, 0.2, # rope
  ]
